### ISSUE TITLE
Connection getting error on click search function not working and database not getting

### ISSUE THREAD

**Issue by aakashpatel1995** [aakashpatel1995/Postgres-Aws#1]
database is not connecting and database is not able to fetch

**Comment by dhruvinparikh93** [comment]
@aakashpatel1995  Please add the steps to run the project and reproduce the error.

**Comment by aakashpatel1995** [comment]
@dhruvinparikh93 added steps in readme 

screen is showing but when try to do onclick function it not works it shows error

**Comment by aakashpatel1995** [comment]
@dhruvinparikh93 still data is not coming or showing

**Comment by dhruvinparikh93** [comment]
Fixed in [PR](https://github.com/aakashpatel1995/Postgres-Aws/pull/4) . @aakashpatel1995 can review and merge.

**Comment by dhruvinparikh93** [comment]
@aakashpatel1995 Close if the issue is solved
